
project_id = "oxeheowbfsshpyldlskb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[[publications]]
publication = "public"
tables = [
  "public.equipments",
  "public.organizations",
  "public.teams",
  "public.users",
  "public.equipment",
  "public.organization_members",
  "public.team_members",
  "public.team_invitations",
  "public.sessions",
  "public.user_profiles",
  "public.worknotes"
]

[studio]
enabled = true
port = 54323
browser_open = false

[functions]
[functions.get_dashboard_data]
verify_jwt = true
