-- =====================================================
-- EquipQR Seed Data - Equipment Location History
-- =====================================================
-- Seeds manual/team_sync history records.
-- Scan-based history entries are generated by triggers from 14_scans.sql.

INSERT INTO public.equipment_location_history (
  id,
  equipment_id,
  source,
  latitude,
  longitude,
  address_street,
  address_city,
  address_state,
  address_country,
  formatted_address,
  changed_by,
  metadata,
  created_at
) VALUES
  -- Manual location changes
  (
    '6d0e8400-e29b-41d4-a716-446655440001'::uuid,
    'aa0e8400-e29b-41d4-a716-446655440001'::uuid, -- John Deere 850L Dozer
    'manual',
    32.7555,
    -97.3308,
    '2000 Industrial Blvd',
    'Fort Worth',
    'TX',
    'US',
    '2000 Industrial Blvd, Fort Worth, TX, US',
    'bb0e8400-e29b-41d4-a716-446655440003'::uuid,
    '{"reason":"operator update","entry_point":"equipment_edit_form"}'::jsonb,
    '2026-01-07 09:16:00+00'
  ),
  (
    '6d0e8400-e29b-41d4-a716-446655440002'::uuid,
    'aa0e8400-e29b-41d4-a716-446655440011'::uuid, -- JLG 450AJ Boom Lift
    'manual',
    37.7749,
    -122.4194,
    '555 California St',
    'San Francisco',
    'CA',
    'US',
    '555 California St, San Francisco, CA, US',
    'bb0e8400-e29b-41d4-a716-446655440005'::uuid,
    '{"reason":"dispatch relocation","entry_point":"equipment_edit_form"}'::jsonb,
    '2026-01-08 12:31:00+00'
  ),
  (
    '6d0e8400-e29b-41d4-a716-446655440003'::uuid,
    'aa0e8400-e29b-41d4-a716-446655440032'::uuid, -- Ingersoll Rand P185 Compressor
    'manual',
    33.7490,
    -84.3880,
    '1000 Northside Dr NW',
    'Atlanta',
    'GA',
    'US',
    '1000 Northside Dr NW, Atlanta, GA, US',
    'bb0e8400-e29b-41d4-a716-446655440007'::uuid,
    '{"reason":"yard reassignment","entry_point":"equipment_edit_form"}'::jsonb,
    '2026-01-06 14:01:00+00'
  ),

  -- Team sync location inheritance changes
  (
    '6d0e8400-e29b-41d4-a716-446655440004'::uuid,
    'aa0e8400-e29b-41d4-a716-446655440000'::uuid, -- CAT 320 Excavator
    'team_sync',
    32.7767,
    -96.7970,
    '1500 Main St',
    'Dallas',
    'TX',
    'US',
    '1500 Main St, Dallas, TX, US',
    'bb0e8400-e29b-41d4-a716-446655440001'::uuid,
    '{"team_id":"880e8400-e29b-41d4-a716-446655440000","trigger":"team_override_enabled"}'::jsonb,
    '2026-01-08 14:35:00+00'
  ),
  (
    '6d0e8400-e29b-41d4-a716-446655440005'::uuid,
    'aa0e8400-e29b-41d4-a716-446655440010'::uuid, -- Bobcat S650 Skid Steer
    'team_sync',
    34.0522,
    -118.2437,
    '2000 Sunset Blvd',
    'Los Angeles',
    'CA',
    'US',
    '2000 Sunset Blvd, Los Angeles, CA, US',
    'bb0e8400-e29b-41d4-a716-446655440005'::uuid,
    '{"team_id":"880e8400-e29b-41d4-a716-446655440002","trigger":"equipment_use_team_location_enabled"}'::jsonb,
    '2026-01-08 10:01:00+00'
  )
ON CONFLICT (id) DO NOTHING;
