version: "3.8"
services:
  typesense:
    image: typesense/typesense:0.25.2
    restart: unless-stopped
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    ports:
      - "8108:8108"
    volumes:
      - ./data:/data
