import { createRoot } from 'react-dom/client'
import '@fontsource/jetbrains-mono/400.css';
import '@fontsource/jetbrains-mono/500.css';
import '@fontsource/jetbrains-mono/600.css';
import '@fontsource/jetbrains-mono/700.css';
import App from './App.tsx'
import './index.css'
import { initConsoleErrorCapture } from '@/features/tickets/utils/consoleErrorBuffer';
import { ErrorBoundary } from '@/components/ui/error-boundary';

// Initialize console error capture for bug report diagnostics
// Must run before React renders so we capture errors during startup
initConsoleErrorCapture();

createRoot(document.getElementById("root")!).render(
  <ErrorBoundary>
    <App />
  </ErrorBoundary>
);

// Register service worker for PWA app-shell caching + push notifications.
// In production the worker is generated by vite-plugin-pwa from `src/sw.ts`;
// in dev it is intentionally not emitted (devOptions.enabled = false in
// vite.config.ts), so registration is skipped to avoid 404 noise.
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  window.addEventListener('load', async () => {
    try {
      const registration = await navigator.serviceWorker.register('/sw.js', {
        scope: '/',
      });

      // Check for updates hourly so a deployed shell upgrade is picked up
      // without requiring the user to fully close and reopen the tab.
      setInterval(() => {
        registration.update();
      }, 60 * 60 * 1000);
    } catch (error) {
      // Service worker registration failed - non-critical for app functionality
      if (import.meta.env.DEV) {
        // eslint-disable-next-line no-console -- intentional dev-only diagnostic
        console.warn('[SW] Service worker registration failed:', error);
      }
    }
  });
}
