
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_CONFIG, APP_CONFIG } from '@/config/environment';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_CONFIG.url,
  SUPABASE_CONFIG.anonKey,
  {
    auth: {
      storage: localStorage, // Use direct localStorage for simplicity and reliability
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      debug: APP_CONFIG.debug // Use environment-based debug setting
    },
    global: {
      headers: {
        'x-client-info': `equipqr-web@${new Date().toISOString().split('T')[0]}`
      }
    }
  }
);

// Set up auth event listener outside the client creation
supabase.auth.onAuthStateChange((event, session) => {
  if (APP_CONFIG.debug) {
    console.log('Client: Auth state change detected:', event);
  }
  if (event === 'SIGNED_OUT') {
    if (APP_CONFIG.debug) {
      console.log('Client: User signed out, clearing local storage');
    }
  }
});
