// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymxkzronkhwxzcdcbnwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteGt6cm9ua2h3eHpjZGNibndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTUyMzUsImV4cCI6MjA2NTY5MTIzNX0.OA-W5d6GE3BaSCPxjG6TBDWtlbNvSN8cEDdkZcujiJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);