name: Auto-merge Version Bump PRs

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - preview

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.title, 'chore: bump version to ') }}
    steps:
      - name: Auto-approve version bump PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.PAT_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

