name: Versioning

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

env:
  MAIN_BRANCH: main
  PREVIEW_BRANCH: preview
  TAG_PREFIX: v

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Determine last tag
        id: last
        shell: bash
        run: |
          set -e
          LAST_TAG=$(git describe --tags --abbrev=0 --match "${TAG_PREFIX}[0-9]*" 2>/dev/null || echo "${TAG_PREFIX}0.0.0")
          echo "last_tag=${LAST_TAG}" >> $GITHUB_OUTPUT
          echo "Found last tag: ${LAST_TAG}"

      - name: Decide bump type
        id: bump
        shell: bash
        run: |
          BASE="${{ github.event.pull_request.base.ref }}"
          HEAD="${{ github.event.pull_request.head.ref }}"
          PREVIEW="${{ env.PREVIEW_BRANCH }}"
          MAIN="${{ env.MAIN_BRANCH }}"

          echo "Base branch: $BASE"
          echo "Head branch: $HEAD"
          echo "Preview branch: $PREVIEW"
          echo "Main branch: $MAIN"

          if [ "$BASE" = "$PREVIEW" ]; then
            BUMP="minor"
            echo "Minor bump: PR to preview branch"
          elif [ "$BASE" = "$MAIN" ]; then
            if [ "$HEAD" = "$PREVIEW" ]; then
              BUMP="major"
              echo "Major bump: Preview to main branch"
            else
              BUMP="patch"
              echo "Patch bump: Feature to main branch"
            fi
          else
            echo "Unsupported base branch '$BASE' – skipping."; echo "skip=true" >> $GITHUB_OUTPUT; exit 0
          fi

          echo "bump_type=${BUMP}" >> $GITHUB_OUTPUT

      - name: Compute new version
        if: steps.bump.outputs.skip != 'true'
        id: newver
        shell: bash
        env:
          LAST: ${{ steps.last.outputs.last_tag }}
          BUMP: ${{ steps.bump.outputs.bump_type }}
          TAG_PREFIX: ${{ env.TAG_PREFIX }}
        run: |
          set -e
          V="${LAST#${TAG_PREFIX}}"
          IFS='.' read -r MA MI PA <<< "$V"
          echo "Current version parts: MAJOR=$MA, MINOR=$MI, PATCH=$PA"
          echo "Bump type: $BUMP"
          
          case "$BUMP" in
            major) MA=$((MA+1)); MI=0; PA=0;;
            minor) MI=$((MI+1)); PA=0;;
            patch) PA=$((PA+1));;
          esac
          
          NEW="${TAG_PREFIX}${MA}.${MI}.${PA}"
          echo "new_tag=${NEW}" >> $GITHUB_OUTPUT
          echo "New tag will be: $NEW"

      - name: Guard if tag exists already
        if: steps.bump.outputs.skip != 'true'
        shell: bash
        env:
          NEW: ${{ steps.newver.outputs.new_tag }}
        run: |
          if git rev-parse "$NEW" >/dev/null 2>&1; then
            echo "Tag $NEW already exists. Exiting."; exit 0
          fi
          echo "Tag $NEW does not exist. Proceeding with creation."

      - name: Create and push tag
        if: steps.bump.outputs.skip != 'true'
        shell: bash
        env:
          NEW: ${{ steps.newver.outputs.new_tag }}
        run: |
          echo "Creating and pushing tag: $NEW"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "$NEW" -m "Automated version bump to $NEW"
          git push origin "$NEW"
          echo "Successfully created and pushed tag: $NEW"

      - name: Output summary
        if: steps.bump.outputs.skip != 'true'
        run: |
          echo "🎉 Version bump completed!"
          echo "Previous tag: ${{ steps.last.outputs.last_tag }}"
          echo "New tag: ${{ steps.newver.outputs.new_tag }}"
          echo "Bump type: ${{ steps.bump.outputs.bump_type }}"